### ISSUE TITLE
Post Card Avatar

### ISSUE THREAD

**Issue by Zevl411** [Ufoatmeal/Trufflr#11]
Location: Trufflr --> client --> src --> components --> Posts --> Post.js

Rendered avatar profile image is not loading the correct creator's profile. 
Only loading the profile image of the user when logged in, nothing when logged out. 

Line 35:
`
<Avatar className={classes.purple} alt={user?.result.name} src={user?.result.imageUrl}>{user?.result.name.charAt(0)}</Avatar>
`

Possible error in: Trufflr --> client --> src --> api --> index.js  regarding profile item.

Can one of you work on this bug? @hplaks106 @austinjsisinni  , Thank You

All work should be done in the avatar_bug branch

**Comment by Tyler-LeCluse** [comment]
index.js:1 Warning: Failed prop type: Material-UI: Either `children`, `image`, `src` or `component` prop must be specified.

This is the error

**Comment by austinjsisinni** [comment]
Fixed.
