### ISSUE TITLE
Talking Topic: (Avatar IMG)

### ISSUE THREAD

**Issue by Tyler-LeCluse** [Ufoatmeal/Trufflr#12]
The "Avatar" component is not rendering the correct user's profile image on the corresponding cards. 

Possible fixes:

1. Require email sign-in. No Google sign-in. Since they are assumed reoccurring users, they will need to have information stored about them such as preferences and such. The Google sign-in eliminates any user information that is saved into the database. This also prevents the database to find any information about the user while attempting to pull in the "CardHeader" component in "client/src/components/Posts/Post/Post.js"
2. Just don't display the user profile image at this point.

**Comment by austinjsisinni** [comment]
Fixed by displaying instead of profile photo, the initials of the recipe creator
